#!/usr/bin/env bash
set -ex

conda install conda=24.9.1
conda update -n base conda
conda install -n base conda-forge::mamba
mamba install -c conda-forge  \
        dask==2024.9.0 \
        dask-image==2024.5.3 \
        distributed==2024.9.0 \
        jupyterlab==3.6.2 \
        matplotlib==3.9.2 \
        numpy==2.1.1 \
        pandas==2.2.3 \
        s3fs==2024.9.0 \
        scikit-image==0.24.0 \
        scipy==1.14.1 \
        seaborn==0.13.2 \
        zarr==2.18.3 \
        s5cmd==2.2.2 \
        cupy 
mamba install -c rapidsai -c conda-forge -c nvidia dask-cuda cuda-version=12.1
mamba install -c rapidsai -c conda-forge cucim cuda-version=12.1
